#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrakker
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbJobTrakker")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblJobTrakker(tblJobTrakker instance);
    partial void UpdatetblJobTrakker(tblJobTrakker instance);
    partial void DeletetblJobTrakker(tblJobTrakker instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::JobTrakker.Properties.Settings.Default.dbJobTrakkerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblJobTrakker> tblJobTrakkers
		{
			get
			{
				return this.GetTable<tblJobTrakker>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblJobTrakker")]
	public partial class tblJobTrakker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ActiveState;
		
		private System.Nullable<bool> _DWSFlag;
		
		private string _Company;
		
		private string _StaffingFirm;
		
		private string _JobTitle;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _ContactDate;
		
		private string _InterviewDateTime;
		
		private string _JobBoard;
		
		private string _JobID;
		
		private string _Contact;
		
		private string _Title;
		
		private string _Phone;
		
		private string _Email;
		
		private System.Nullable<bool> _RecruiterFlag;
		
		private string _Address;
		
		private string _JobLocation;
		
		private string _CompanyPhone;
		
		private string _WebSite;
		
		private string _Comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnActiveStateChanging(string value);
    partial void OnActiveStateChanged();
    partial void OnDWSFlagChanging(System.Nullable<bool> value);
    partial void OnDWSFlagChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnStaffingFirmChanging(string value);
    partial void OnStaffingFirmChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnContactDateChanging(System.Nullable<System.DateTime> value);
    partial void OnContactDateChanged();
    partial void OnInterviewDateTimeChanging(string value);
    partial void OnInterviewDateTimeChanged();
    partial void OnJobBoardChanging(string value);
    partial void OnJobBoardChanged();
    partial void OnJobIDChanging(string value);
    partial void OnJobIDChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRecruiterFlagChanging(System.Nullable<bool> value);
    partial void OnRecruiterFlagChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnJobLocationChanging(string value);
    partial void OnJobLocationChanged();
    partial void OnCompanyPhoneChanging(string value);
    partial void OnCompanyPhoneChanged();
    partial void OnWebSiteChanging(string value);
    partial void OnWebSiteChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public tblJobTrakker()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="NChar(10)")]
		public string ActiveState
		{
			get
			{
				return this._ActiveState;
			}
			set
			{
				if ((this._ActiveState != value))
				{
					this.OnActiveStateChanging(value);
					this.SendPropertyChanging();
					this._ActiveState = value;
					this.SendPropertyChanged("ActiveState");
					this.OnActiveStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWSFlag", DbType="Bit")]
		public System.Nullable<bool> DWSFlag
		{
			get
			{
				return this._DWSFlag;
			}
			set
			{
				if ((this._DWSFlag != value))
				{
					this.OnDWSFlagChanging(value);
					this.SendPropertyChanging();
					this._DWSFlag = value;
					this.SendPropertyChanged("DWSFlag");
					this.OnDWSFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(100)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffingFirm", DbType="NVarChar(100)")]
		public string StaffingFirm
		{
			get
			{
				return this._StaffingFirm;
			}
			set
			{
				if ((this._StaffingFirm != value))
				{
					this.OnStaffingFirmChanging(value);
					this.SendPropertyChanging();
					this._StaffingFirm = value;
					this.SendPropertyChanged("StaffingFirm");
					this.OnStaffingFirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(100)")]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(100)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactDate", DbType="Date")]
		public System.Nullable<System.DateTime> ContactDate
		{
			get
			{
				return this._ContactDate;
			}
			set
			{
				if ((this._ContactDate != value))
				{
					this.OnContactDateChanging(value);
					this.SendPropertyChanging();
					this._ContactDate = value;
					this.SendPropertyChanged("ContactDate");
					this.OnContactDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterviewDateTime", DbType="VarChar(50)")]
		public string InterviewDateTime
		{
			get
			{
				return this._InterviewDateTime;
			}
			set
			{
				if ((this._InterviewDateTime != value))
				{
					this.OnInterviewDateTimeChanging(value);
					this.SendPropertyChanging();
					this._InterviewDateTime = value;
					this.SendPropertyChanged("InterviewDateTime");
					this.OnInterviewDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobBoard", DbType="VarChar(100)")]
		public string JobBoard
		{
			get
			{
				return this._JobBoard;
			}
			set
			{
				if ((this._JobBoard != value))
				{
					this.OnJobBoardChanging(value);
					this.SendPropertyChanging();
					this._JobBoard = value;
					this.SendPropertyChanged("JobBoard");
					this.OnJobBoardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", DbType="NVarChar(50)")]
		public string JobID
		{
			get
			{
				return this._JobID;
			}
			set
			{
				if ((this._JobID != value))
				{
					this.OnJobIDChanging(value);
					this.SendPropertyChanging();
					this._JobID = value;
					this.SendPropertyChanged("JobID");
					this.OnJobIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(100)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecruiterFlag", DbType="Bit")]
		public System.Nullable<bool> RecruiterFlag
		{
			get
			{
				return this._RecruiterFlag;
			}
			set
			{
				if ((this._RecruiterFlag != value))
				{
					this.OnRecruiterFlagChanging(value);
					this.SendPropertyChanging();
					this._RecruiterFlag = value;
					this.SendPropertyChanged("RecruiterFlag");
					this.OnRecruiterFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobLocation", DbType="VarChar(250)")]
		public string JobLocation
		{
			get
			{
				return this._JobLocation;
			}
			set
			{
				if ((this._JobLocation != value))
				{
					this.OnJobLocationChanging(value);
					this.SendPropertyChanging();
					this._JobLocation = value;
					this.SendPropertyChanged("JobLocation");
					this.OnJobLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyPhone", DbType="NVarChar(50)")]
		public string CompanyPhone
		{
			get
			{
				return this._CompanyPhone;
			}
			set
			{
				if ((this._CompanyPhone != value))
				{
					this.OnCompanyPhoneChanging(value);
					this.SendPropertyChanging();
					this._CompanyPhone = value;
					this.SendPropertyChanged("CompanyPhone");
					this.OnCompanyPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSite", DbType="NVarChar(250)")]
		public string WebSite
		{
			get
			{
				return this._WebSite;
			}
			set
			{
				if ((this._WebSite != value))
				{
					this.OnWebSiteChanging(value);
					this.SendPropertyChanging();
					this._WebSite = value;
					this.SendPropertyChanged("WebSite");
					this.OnWebSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
